#!/bin/bash

# This script obtain the temperature efects.
# Script made by Ely Miranda, PhD student at Physics Institute in Universidade de São Paulo
# Last update: 22/03/2023
# Any question or suggestion write me: ely.miranda@usp.br :)