#!/bin/bash

# This script obtain the temperature efects.
# Script made by Ely Miranda, PhD student at Physics Institute in Universidade de São Paulo
# Last update: 22/03/2023
# Any question or suggestion write me: ely.miranda@usp.br :)

R=0.00000316679085237                                     # Kelvin to Hartree
NA=6.02214086e23
kB=$(echo "$R/$NA" | bc)
P_conv=3.4439667564003e-9                                 # atm to a.u.
mass_conv=1836.15267389                                   # a.m.u to a.u.